### ISSUE TITLE
Auto layout is not coming properly

### ISSUE THREAD

**Issue by bhupesh-sf** [denis-mrd/dbdiagram-oss#7]
I have created a DB schema using dbml but its not coming as proper. I have 62 tables with 3 Table groups (includes 5-7 tables) and all other tables independent.

Can you please see if this can be corrected? Also glowing all ref by default?

**Comment by deniszagitov** [comment]
Hello, Bhupesh!
I think you are trying to use "Table groups" - paid feature of dbdiagram: https://docs.dbdiagram.io/table-groups.
It works here just like this:
```
TableGroup "HubsTestGroup" {
  HubUser
  HubPromocode
}
```
I added feature for glowing constraints with that logic: you have to click on some regular line and it become red
